### PR TITLE
Making form links

### PR DESCRIPTION
**Pull request by alantly**

### CODE REVIEW

**Comment by alantly** [comment]
Don't merge this just yet, gonna add a bit more functionnality. ill put a comment when it is ready, this is just for show

**Comment by hyunskang** [comment]
Can you add an explanation on how the new model Application Type will be used?

**Comment by alantly** [comment]
The way it will be used is just through the seed file. We just won't show them that they can created application types. Otherwise we need to create the controller and view to work with it. This way, we have less work and our implementation can expand. hopefully

**Comment by alantly** [comment]
Im done, it is ready for merge.

**Pull request merged**
